# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: @project.build.sourceEncoding@
  application.name: ${spring.application.name}
  spring.boot.version: @spring-boot.version@

server:
  shutdown: graceful

spring:
  application:
    name: spring-boot-new-features
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  health:
     probes:
       enabled: true

endpoint:
  health:
    show-details: always

debug: true
